CREATE TABLE `uprtcc` (
  `id` tinytext,
  `acc` text,
  `ra` text,
  `rx` text,
  `dt` tinytext,
  `de` tinytext,
  `gn` tinytext,
  `os` tinytext,
  `oc` text,
  `ox` tinytext,
  `oh` text,
  `rp` tinytext,
  `rt` text,
  `rl` tinytext,
  `dr` text,
  `pe` tinytext,
  `kw` text,
  `ft` text,
  `sq` tinytext,
  `seq` text,
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `cc` text,
  PRIMARY KEY (`uid`),
  KEY `unip` (`id`(5)),
  FULLTEXT KEY `uniac` (`acc`),
  FULLTEXT KEY `gni` (`gn`),
  FULLTEXT KEY `osi` (`os`),
  FULLTEXT KEY `dei` (`de`)
) ENGINE=MyISAM AUTO_INCREMENT=3646231 DEFAULT CHARSET=latin1;

